language: scala
script: sbt ';set scalaVersion in Global := "2.10.1"; test-only * -- -exclude testCommands --'
scala:
  - "2.10.1"
  - "2.10.0"
jdk:
  - oraclejdk7
  - openjdk7
  - openjdk6
services:
  - mongodb
