language: scala
script: sbt ++$TRAVIS_SCALA_VERSION "testOnly * -- -exclude testCommands,mongo2_4 --"
scala:
  - "2.11.1"
  - "2.10.4"
jdk:
  - oraclejdk7
  - openjdk7
  - openjdk6
services:
  - mongodb
